# Generated by Django 4.2 on 2023-04-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elevator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elevator",
            name="elevator_name",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
